# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Install sbt'
  inputs:
    targetType: 'inline'
    script: 'apt-get update; apt-get --yes install wget; wget https://dl.bintray.com/sbt/debian/sbt-1.2.8.deb; dpkg -i sbt-1.2.8.deb;'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sbt compile'